// Generated by SugarLisp v0.6.6



var Component = function(title) {

  var test = (1 + 1);

  return <div>
      
      <h1>
        {title}
      </h1>
      <p>
        Lorem ipsum dolor...
      </p>
      <p>
        
        <span>
          {test}
        </span>
      </p>
    </div>;
};